### ISSUE TITLE
raise MemoryError when I run prepro.py

### ISSUE THREAD

**Issue by zjjott** [yunjey/show-attend-and-tell-tensorflow#4]
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:944] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.8095
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.27GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
Loaded ./data/train/train.annotations.pkl..

Traceback (most recent call last):
  File "prepro.py", line 234, in <module>
    main()
  File "prepro.py", line 209, in main
    all_feats = np.ndarray([n_examples, 196, 512], dtype=np.float32)
MemoryError

```
I print n_examples,and there have 80k images, so 82783x196x512= 8307439616,float32 is 32bit,so there will be 8,307,439,616 *32bit=32GB memory ?  
Is there some wrong?

My 1080 have 7.27GB free memory,so I change n_example to 20000,all things work well

**Comment by yunjey** [comment]
np.ndarray is a numpy object so the required memory is related to cpu memory not gpu memory. If you don't have enough cpu memory, i recommend to reduce the number of training dataset.

**Comment by linrio** [comment]
@yunjey How to reduce the number of training dataset?
