### ISSUE TITLE
In prepro.py File, line 31:  caption_data.sort_values(by='image_id', inplace=True) 

### ISSUE THREAD

**Issue by cnliuy** [yunjey/show-attend-and-tell-tensorflow#8]
~/show-attend-and-tell-tensorflow# **python prepro.py** 
Traceback (most recent call last):
  File "prepro.py", line 212, in <module>
    main()
  File "prepro.py", line 138, in main
    max_length=max_length)
  File "prepro.py", line 31, in _process_caption_data
    caption_data.sort_values(by='image_id', inplace=True)
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 1815, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataFrame' object has no attribute 'sort_values'

in  prepro.py :
line31      caption_data.sort_values(by='image_id', inplace=True)

**Comment by bongmo** [comment]
I solved this problem by upgrading pandas library version from (0.13.x -> 0.19.x)
