### ISSUE TITLE
Error running evaluate_model.ipynb

### ISSUE THREAD

**Issue by slcott** [yunjey/show-attend-and-tell-tensorflow#9]
Maybe you can help me run your excellent project.

After following all steps of the README, an error occurs on the last step: 
> To generate captions, visualize attention weights and evaluate the model, please see evaluate_model.ipynb

When trying to run: `solver.test(data, split='val')` an ipython notebook error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-bd97c6083ed6> in <module>()
----> 1 solver.test(data, split='val')

/Users/slcott/Desktop/show-attend-and-tell-tensorflow/core/solver.pyc in test(self, data, split, attention_visualization, save_sampled_captions)
    187 
    188         # build a graph to sample captions
--> 189         alphas, betas, sampled_captions = self.model.build_sampler(max_len=20)    # (N, max_len, L), (N, max_len)
    190 
    191         config = tf.ConfigProto(allow_soft_placement=True)

/Users/slcott/Desktop/show-attend-and-tell-tensorflow/core/model.pyc in build_sampler(self, max_len)
    183 
    184         # batch normalize feature vectors
--> 185         features = self._batch_norm(features, mode='test', name='conv_features')
    186 
    187         c, h = self._get_initial_lstm(features=features)

/Users/slcott/Desktop/show-attend-and-tell-tensorflow/core/model.pyc in _batch_norm(self, x, mode, name)
    135                                             is_training=(mode=='train'),
    136                                             updates_collections=None,
--> 137                                             scope=(name+'batch_norm'))
    138 
    139     def build_model(self):

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.pyc in func_with_args(*args, **kwargs)
    175       current_args = current_scope[key_func].copy()
    176       current_args.update(kwargs)
--> 177     return func(*args, **current_args)
    178   _add_op(func)
    179   setattr(func_with_args, '_key_op', _key_op(func))

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.pyc in batch_norm(inputs, decay, center, scale, epsilon, activation_fn, param_initializers, updates_collections, is_training, reuse, variables_collections, outputs_collections, trainable, batch_weights, fused, data_format, scope)
    515                                       initializer=beta_initializer,
    516                                       collections=beta_collections,
--> 517                                       trainable=trainable)
    518     if scale:
    519       gamma_collections = utils.get_variable_collections(variables_collections,

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.pyc in func_with_args(*args, **kwargs)
    175       current_args = current_scope[key_func].copy()
    176       current_args.update(kwargs)
--> 177     return func(*args, **current_args)
    178   _add_op(func)
    179   setattr(func_with_args, '_key_op', _key_op(func))

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.pyc in model_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, device)
    242                   initializer=initializer, regularizer=regularizer,
    243                   trainable=trainable, collections=collections,
--> 244                   caching_device=caching_device, device=device)
    245 
    246 

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.pyc in func_with_args(*args, **kwargs)
    175       current_args = current_scope[key_func].copy()
    176       current_args.update(kwargs)
--> 177     return func(*args, **current_args)
    178   _add_op(func)
    179   setattr(func_with_args, '_key_op', _key_op(func))

/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.pyc in variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, device)
    206                                        trainable=trainable,
    207                                        collections=collections,
--> 208                                        caching_device=caching_device)
    209 
    210 

/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, custom_getter)
   1022       collections=collections, caching_device=caching_device,
   1023       partitioner=partitioner, validate_shape=validate_shape,
-> 1024       custom_getter=custom_getter)
   1025 
   1026 

/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, custom_getter)
    848           collections=collections, caching_device=caching_device,
    849           partitioner=partitioner, validate_shape=validate_shape,
--> 850           custom_getter=custom_getter)
    851 
    852   def _get_partitioned_variable(self,

/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, custom_getter)
    344           reuse=reuse, trainable=trainable, collections=collections,
    345           caching_device=caching_device, partitioner=partitioner,
--> 346           validate_shape=validate_shape)
    347 
    348   def _get_partitioned_variable(

/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape)
    329           initializer=initializer, regularizer=regularizer, reuse=reuse,
    330           trainable=trainable, collections=collections,
--> 331           caching_device=caching_device, validate_shape=validate_shape)
    332 
    333     if custom_getter is not None:

/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape)
    630                          " Did you mean to set reuse=True in VarScope? "
    631                          "Originally defined at:\n\n%s" % (
--> 632                              name, "".join(traceback.format_list(tb))))
    633       found_var = self._vars[name]
    634       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable conv_featuresbatch_norm/beta already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 208, in variable
    caching_device=caching_device)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 244, in model_variable
    caching_device=caching_device, device=device)
```

My guess is that something is wrong with my tensorflow installation, which is weird because I tested it out with [basic usage](https://www.tensorflow.org/get_started/basic_usage) in iPython and everything works fine there. 

Do you see what is causing my problem?

**Comment by yunjey** [comment]
If you run both solver.train () and solver.test (), you get an error. This is because tf.get_variable() is used in both functions. The solution to this problem is to run solver.test () only once, as in evaluate_model.ipynb.

**Comment by slcott** [comment]
My first error was that I forgot to run `train.py`.  It took 12 hours running `prepro.py`. And then my computer ran out of memory running `train.py`. 

My laptop has 16 GB of RAM. Is this not enough? Maybe I should use an AWS GPU machine instead?

**Comment by yunjey** [comment]
I recommend  running the code using gpu. If you want to run this code on your cpu, try reducing batch size and running the code.

**Comment by slcott** [comment]
I tracked down the line of code causing the memory over-usage:

```
data = load_coco_data(data_path='./data', split='train')
```
in `train.py`

The `data/train` directory occupies 33.36 GB on my drive.
`train.features.hkl` is 33.23 GB.

Is that unusual? 

If not, I think I'm gonna try and [use a queue or something like it](https://www.tensorflow.org/how_tos/reading_data/) to stream the data rather than reading all of it at the same time.
